[package]
name = "sqlit"
version = "0.1.0"
authors = ["max <frismo98@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
regex = "0.1.41"
rayon = "1.5.0"
time-test = "0.2.2"
